### ISSUE TITLE
Semantics - Simplify Event Registration

### ISSUE THREAD

**Issue by austinjlaverty** [pricelinelabs/omni-slider#15]
This is just semantics, and of course up to debate, but I believe it can help make using the slider's API more readable.

```js
slider.subscribe('moving', handleOnSliderMove);
```
vs

```js
slilder.on('move', handleOnSliderMove)
```

You could remove `subscribe` altogether, or also offer an `on` method that internally calls `subscribe`.

**Comment by chrisrng** [comment]
What was your idea here? Instead of doing `subscribe` we do `on`? Seems essentially the same thing except we don't support a lot of the traditionally used `on` methods such as click, resize, etc.

Do you think we should cater to those events as well?

**Comment by bcVamp** [comment]
Just 2 cents: think the more modern naming convention or pattern name is `pub/sub` such as `.publish` and `.subscribe`. Some companies would use `.dispatch` and `.register`.

I also agree that `.on` sounds a little bit `es5`.

**Comment by austinjlaverty** [comment]
It is the exact same thing, its just less to type and I'm arguing it can be more readable and expressive within the context of a UI element. 

My thinking behind this is because `.on` is often used to replace the more verbose `.addEventListener`, which as you know, is the native way to listen out for an event from a DOM element like a slider. It also works great with `on` `once` `off` and `fire`. No one said because a method is named a particular way you are required to fire off specific events like `click`; it's just a name.

The fact that you thought of click and resize is exactly what I'm getting at. You see the method name `on` and you think "oh, this must be for listening to a UI event". Many modern UI libraries still use this naming convention. Polymer, as an example, requires events to be prefixed with the word `on-` when registering callbacks through markup: ``<slider on-move="handleOnMove">`
