### ISSUE TITLE
 eslint support issue - Parsing error: Illegal export declaration?

### ISSUE THREAD

**Issue by bcVamp** [pricelinelabs/omni-slider#18]
Hello,

I experimented to gauge how supportive the eslint or language feature this code base supports with the following snippet in the screen.

I was unlucky to get a "yelling" for a `eslint` parsing error with a simple usage of `export`?

`Parsing error: Illegal export declaration` - Please see following IDE analysis and help the contributors to understand how supportive of `es2015` language features this code base supports?

<img width="668" alt="screen shot 2016-06-09 at 8 30 14 am" src="https://cloud.githubusercontent.com/assets/19755488/15929693/748a80bc-2e1c-11e6-8761-51f6245bf8d1.png">

**Comment by bcVamp** [comment]
Hi @thehindenburg , heart that you are savvy with linter config and toolset. Do you know why the `eslint` would not support a simple `export` language feature?

**Comment by thehindenburg** [comment]
When eslint was turned on, it was turned on without a `.eslintconfig`. I'm implementing Priceline's linter momentarily, you can follow that PR here: https://github.com/pricelinelabs/javascript/pull/1

**Comment by chrisrng** [comment]
This should be fixed with #20

**Comment by bcVamp** [comment]
Thanks guys. Let's enable full language feature support for at least `es2015`, if not `es2016`. I got a couple of ideas to implement the open issues using es2015 stuff to explore things. Need the linter to be easy on me. :)

**Comment by thehindenburg** [comment]
This is the linter we're using internally which is taking full advantage of `async/await` and other es2016 features, so should be fully formed and ready for your future needs. :)
