### ISSUE TITLE
Squash commits

### ISSUE THREAD

**Issue by thehindenburg** [pricelinelabs/omni-slider#19]
I would recommend squashing commits. It's already kind of a zoo in there

**Comment by chrisrng** [comment]
Do you know anyway we can mandate that?

**Comment by thehindenburg** [comment]
I would just have a strict "squash before PR" rule, we can talk more offline

**Comment by bcVamp** [comment]
@chrisrng & @thehindenburg,

Totally digging the 'squashing-commit` workflow before PR, in favor of keeping history tidy and easier to digest.

Question:
If a developer builds a feature which takes stable phases, before they feel product-ready to submit the PR, _**would the squashed version consolidate all the developer's stable baselines in the planned & scoped commits & commit messages into one single, summarized version**_?

The user story would be:
* Before the squashed version: (from most recent to earliest)
```
feat(0.3): Products
feat(0.2): State Machine
feat(0.1): API
```

How would the squashed version look like?

**Comment by thehindenburg** [comment]
No, you can definitely still have multiple commits in a PR. The idea is that there should be logical commits that have a separation of concern. If you're building a larger feature it may make sense to have 3 or 4 commits, but make sure that each section your working on goes into just those three or four commits, not a conglomerate of small commits that make up one section, if that makes sense. It really just depends on the size of the PR. The idea to shoot for is "in the future if someone is only looking at commits, what would be a meaningful commit to look at?" and try and keep all commits bundled with that thought in mind.
