### ISSUE TITLE
No `develop` branch for gitflow?

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/omni-slider#2]
Hello,

Saw a few places where I'd like to explore to perhaps refactor a few things. Does this repo need to adapt gitflow if people want to contribute back, @chrisrng ?

**Comment by chrisrng** [comment]
Hi, Good question - we will be using [Github Flow](https://guides.github.com/introduction/flow/) as this is standard for projects here. And so there would be no need for a `develop` branch. Please create a Pull Request for your changes.

**Comment by BeniCheni** [comment]
Sounds good. I am creating another issue to discuss a question to deem if it's something you'd like to fix first, before I execute the code. Look out for the next issue.
