### ISSUE TITLE
es2015 Support Issue on simple 'import'?

### ISSUE THREAD

**Issue by ghost** [pricelinelabs/omni-slider#26]
Ran into this `Parsing error: Illegal import declaration` with the regular `npm start` script, and a simple top-level import statement.

Can the linter pass this as a legal import? This may be blocking some of the features developers are experimenting when more modularized, architecture feature code.

<img width="957" alt="screen shot 2016-06-14 at 5 21 23 pm" src="https://cloud.githubusercontent.com/assets/19755488/16061243/078e8e26-325a-11e6-8b73-060e005bceec.png">

**Comment by chrisrng** [comment]
@thehindenburg can you suggest? Not familiar with this sorry

**Comment by joshbDev** [comment]
I'm not getting this locally, will try to reproduce and get back to you

**Comment by joshbDev** [comment]
@bcVamp would you mind committing and pushing your branch up? I'm unable to duplicate and I've tried on several computers.

**Comment by ghost** [comment]
Sure I can give it a try later with closer attention and another attempt of the npm install cycle. No urgency. Will post screen shot of my attempt again.

**Comment by ghost** [comment]
Confirmed the latest `master` is working. Something was acting up in my earlier attempt in my other personal Mac. Closing.
