### ISSUE TITLE
How to update current value?

### ISSUE THREAD

**Issue by notrealdev** [pricelinelabs/omni-slider#28]
Hi, i have small question?
My default slider run from: 1 to 100, i move it to 15 ( start point ) and 95 ( end point )
How can i reset to default ( 1-100 ) without move handle? i.e click to `button` ?

**Comment by chrisrng** [comment]
Hi there,

You can use the `move()` function detailed here: https://github.com/pricelinelabs/omni-slider#preset-a-slider-value

**Comment by notrealdev** [comment]
Thank you for the suggestions....I will try
